// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.AltTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseIncomePerSecond")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BaseUpgradePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Rank")
                        .IsUnique();

                    b.ToTable("AltTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseIncomePerSecond = 1m,
                            BaseUpgradePrice = 10m,
                            BuyPrice = 0m,
                            Name = "Student",
                            Rank = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseIncomePerSecond = 5m,
                            BaseUpgradePrice = 50m,
                            BuyPrice = 100m,
                            Name = "Activist",
                            Rank = 2
                        },
                        new
                        {
                            Id = 3,
                            BaseIncomePerSecond = 25m,
                            BaseUpgradePrice = 250m,
                            BuyPrice = 500m,
                            Name = "Deputy",
                            Rank = 3
                        },
                        new
                        {
                            Id = 4,
                            BaseIncomePerSecond = 150m,
                            BaseUpgradePrice = 1000m,
                            BuyPrice = 2500m,
                            Name = "Minister",
                            Rank = 4
                        });
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("ClickLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastIncomeAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Entities.UserAlts", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AltTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "AltTypeId");

                    b.HasIndex("AltTypeId");

                    b.ToTable("UserAlts");
                });

            modelBuilder.Entity("backend.Entities.UserAlts", b =>
                {
                    b.HasOne("backend.Entities.AltTypes", "AltType")
                        .WithMany()
                        .HasForeignKey("AltTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.User", "User")
                        .WithMany("Alts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AltType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Entities.User", b =>
                {
                    b.Navigation("Alts");
                });
#pragma warning restore 612, 618
        }
    }
}
